version: '3'
services:
    final-franquicia-db:
      image: mariadb:10.4.4
      container_name: final-franquicia-db-dev
      restart: unless-stopped
      environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=finalfranquicia
      command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default_time_zone=-03:00 --net-read-timeout=60 --net-write-timeout=120 --max-allowed-packet=536870912 --wait-timeout=1850 --interactive-timeout=1850
      networks:
        - final-franquicia-backend-dev
      volumes:
        - mariadb-final-franquicia:/var/lib/mysql

    final-franquicia-backend:
      image: jhipster/jhipster
      container_name: final-franquicia-backend-dev
      restart: unless-stopped
      depends_on:
        - final-franquicia-db
      ports:
        - '8080:8080'
        - '9000:9000'
        - '3001:3001'
      networks:
        - final-franquicia-backend-dev
      volumes:
        - ~/Facultad/Final-Franquicia:/home/jhipster/app
        - ~/Facultad/Final-Franquicia/.m2:/home/jhipster/.m2

networks:
  final-franquicia-backend-dev:
    driver: 'bridge'

volumes:
  mariadb-final-franquicia:
